- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "/var/snap/jenkins/4865/workspace/myansi/target/myansi.war"
        dest: "/opt/tomcat/webapps/"
        remote_src: no

    
